import os
import json
import datetime
import maya.cmds as cmds
from functools import partial

"""

Write metadata JSON for referenced assets.

args:
    asset : Asset name
    version : Asset version currently applied
"""

def write_metadata(asset, version):
    data_dir = os.path.join(cmds.workspace(q=True, rd=True), "data")
    metadata_file = os.path.join(data_dir, f"{asset}.reference.json")

    asset_metadata = {
        "asset": asset,
        "version": version,
        "referenced_by": cmds.file(q=True, sn=True),
        "date_referenced": datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "maya_user": os.getenv("USERNAME") or os.getenv("USER") or "unknown"
    }

    with open(metadata_file, 'w') as f:
        json.dump(asset_metadata, f)

    print(f"Asset metadata written to '{metadata_file}'.")

"""
Read asset directory from environment variable 'ASSET_DIR' or from scenes folder in current directory.

"""
ASSET_DIR = os.getenv('ASSET_DIR')
if not ASSET_DIR:
    cmds.warning("ASSET_DIR not set. Defaulting to current scenes directory.")
    ASSET_DIR = os.path.join(cmds.workspace(q=True, rd=True), "scenes")


"""
Gets all maya binary files from directory.
Finds files that follow naming convention 'ASSET.model.VERSION.mb'.
Returns dictionary of assets with their versions.

"""
def get_asset_versions(*args):
    files = cmds.getFileList(folder=ASSET_DIR, filespec='*.mb')
    assets = {}
    
    for f in files:
        parts = f.split('.')
        if len(parts) >= 3 and parts[1] == 'model':
            asset = parts[0]
            version = parts[2]
            assets.setdefault(asset, []).append(version)
        
    return assets
    
    
"""
Updates version dropdown in UI window based on the selected asset.

args: 
    asset : Selected asset name ([ASSET] in ASSET.model.VERSION.mb)
    version_options : Version dropdown in UI window
    assets_dict : Dictionary generated by get_asset_versions()
"""
def update_version_options(asset, version_options, assets_dict, *args):
    cmds.optionMenu(version_options, e=True, dai=True)
    if asset in assets_dict:
        for v in assets_dict[asset]:
            cmds.menuItem(label=v, parent=version_options)


"""
References selected maya binary file.
If asset has not been referenced yet, load reference. Otherwise, replaces asset reference with the selected version.

args: 
    asset_field : Selected asset name from UI asset dropdown
    version_field : Selected version name from UI version dropdown
"""    
def apply_reference(asset_field, version_field, *args):
    asset = cmds.optionMenu(asset_field, q=True, value=True)
    version = cmds.optionMenu(version_field, q=True, value=True)
    filename = f"{asset}.model.{version}.mb"
    filepath = os.path.join(ASSET_DIR, filename)
    
    if not os.path.exists(filepath):
        cmds.warning(f"File not found: {filepath}")
        return
    
    ref_namespace = asset
    ref_node = None
    
    #Loops through all referenced file paths in the scene and compares each node's namespace to the selected asset's name
    for ref in cmds.file(q=True, reference=True):
        ref_node_name = cmds.referenceQuery(ref, referenceNode=True)
        ref_ns = cmds.referenceQuery(ref_node_name, namespace=True)
        if ref_ns.strip(':') == ref_namespace:
            ref_node = ref_node_name
            break
            
    if ref_node:
        print(f"Replacing reference for '{ref_namespace}' with '{filename}'")
        cmds.file(filepath, loadReference=ref_node)
    else:
        print(f"Creating new reference for '{ref_namespace}' with '{filename}'")
        cmds.file(filepath, reference=True, namespace=ref_namespace)

    write_metadata(asset, version)
"""
Set up UI window with a dropdown for assets and versions.
"""
def populate_window():
    # Clear any previous reference manager window
    if cmds.window("reference_manager_window", exists=True):
        cmds.deleteUI("reference_manager_window")
    
    win = cmds.window("reference_manager_window", title="Reference Manager")
    col = cmds.columnLayout(parent=win)
    
    assets_dict = get_asset_versions()
    if not assets_dict:
        cmds.warning(f"No .mb files found in '{ASSET_DIR}'.")
    
    asset_names = sorted(assets_dict.keys())
    
    row_1 = cmds.rowLayout(numberOfColumns=1, parent=col)
    cmds.text(label="Select Asset and Version to reference: ", parent=row_1)
    
    row_2 = cmds.rowLayout(numberOfColumns=4, parent=col)
    asset_field = cmds.optionMenu(parent=row_2)
    for asset in asset_names:
        cmds.menuItem(label=asset)
    cmds.text(label=".model.")
    version_field = cmds.optionMenu(parent=row_2)
    cmds.menuItem(label="-")
    cmds.text(label=".mb")
    
    if asset_names:
        update_version_options(asset_names[0], version_field, assets_dict)
        
    cmds.optionMenu(asset_field, e=True, changeCommand=partial(update_version_options, version_options=version_field, assets_dict=assets_dict))
    
    cmds.setParent(col)
    cmds.button(label="Apply Reference", command=partial(apply_reference, asset_field, version_field))
    
    cmds.showWindow(win)

populate_window()